---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
  namespace: pipeline-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: harunakts94/harunodev:1.0
        imagePullPolicy: Always
        name: myweb
      nodeName: worker1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: myweb
  namespace: pipeline-demo
spec:
  ports:
  - nodePort: 32223
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myweb
  type: NodePort
